### PR TITLE
Fix cwd URL so it matches what is found on cp

### PR DESCRIPTION
**Pull request by alecw**
Previous code got a URL which ended with "/./", which failed comparisou with what JVMUtils.getClasspathURLs returns.

### CODE REVIEW

**Comment by rpoplin** [comment]
Oops, this looks like it has been forgotten. @droazen, Can you please review this PR and stick it in our development repo?

**Comment by droazen** [comment]
@rpoplin This wasn't forgotten -- Alec submitted a patch against our unstable repo, and it was merged last December. We just forgot to close out this pull request, which I will do now.

**Comment by rpoplin** [comment]
Great! Thanks.

**Comment by broadgsa** [comment]
Closing -- this was merged into our development branch.

**Pull request closed without merging**
