### PR TITLE
DoC of overlapping genes

### PR DESCRIPTION
**Pull request by seru71**
I have discovered that coverage stats generated for an interval are attributed only to the first gene on the list that overlaps the interval. Subsequent genes overlapping the interval are ignored. Here is a simple fix.

### CODE REVIEW

**Comment by vdauwera** [comment]
@ronlevine Would you be able to look at this PR please? This sounds like something that would be useful for a lot of users but someone needs to check that it passes tests and also add a test for the new functionality. May need to ask the user for a test case.

**Comment by ronlevine** [comment]
@vdauwera Will do.

**Comment by ronlevine** [comment]
@seru71 Please add integration tests.

**Comment by vdauwera** [comment]
@ronlevine External users don't have access to our testing infrastructure
so we need to add the tests ourselves. We can however request a test case.

On Tue, Mar 1, 2016 at 10:03 AM Ron Levine <notifications@github.com> wrote:

> @seru71 <https://github.com/seru71> Please add integration tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadgsa/gatk/pull/16#issuecomment-190757796>.
>
-- 
Geraldine A. Van der Auwera, PhD
Manager of Outreach and Communications
Data Sciences and Data Engineering
Broad Institute

**Comment by ronlevine** [comment]
@seru71 Do you have a test case that exercises this fix?

**Comment by seru71** [comment]
Yes, I will post it in a moment. Need to recap a bit first.

**Comment by seru71** [comment]
I uploaded some test files here http://gatkforums.broadinstitute.org/gatk/discussion/comment/27870

**Comment by seru71** [comment]
I used bams from exome-seq, but any will do. In case of no coverage the
stats would just show 0. Reference genome was b37 from GATK's bundle.

**Comment by vdauwera** [comment]
This was merged in and is available in version 3.6. Thanks @seru71 for your contribution!

**Pull request closed without merging**
